### ISSUE TITLE
Demo is broken

### ISSUE THREAD

**Issue by bramus** [Dachande663/Plex-Export#14]
GET http://hybridlogic.co.uk/experiments/plex/plex-data/data.js 404 (Not Found)

**Comment by MichaelHub** [comment]
I know this fell to the bottom of your list, but I'd recommend updating the link (http://l0ke.com/plex), as it seems to direct to a very sketchy website now.

**Comment by Dachande663** [comment]
Ah that was an old domain that's been squatted now, cheers for pointing it out. I've updated the link direct to GitHub.
