### ISSUE TITLE
"Error: Could not load thumbnail for" if non-localhost

### ISSUE THREAD

**Issue by Commifreak** [Dachande663/Plex-Export#21]
Hi,

I get the following error:

```
Error: Could not load thumbnail for
```

If the host is not on localhost. I try to access Plex via token. So, the calculated url is:

```
http://myplexhost:32400/photo/:/transcode?width=150&height=250&url=http%3A%2F%2Fs2.kluthr.de%3A32400%2Flibrary%2Fmetadata%2F996%2Fthumb%2F1418395105
```

But I get:

```
401 Unauthorized
```

Exists a workaroung for that?

UsingPlex-Web 2.3.20 and Plex 0.9.11.7 together with 1451a04434

**Comment by ukdtom** [comment]
Wrong Token perhaps?
Try and re-verify

**Comment by Commifreak** [comment]
Nope. The connection itself is ok. The posted error shows up for every  found movie. The scan itself is ok, but cli is not able to fetch Thumbnails for every found movie.

**Comment by Commifreak** [comment]
Log:

```
Welcome to the Plex Exporter v1
Searching for sections in the Plex library at http://myplexhost:32400/
Found 1 section in this Plex library
Scanning section: Filme
Found 518 movies in Filme
Scanning movie: *moviename*
Error: Could not load thumbnail for *moviename*
Scanning movie: *moviename2*
Error: Could not load thumbnail for *moviename2*
[...]
```

**Comment by Commifreak** [comment]
Update:

If I provide &X-Plex-Token=[TOKEN] to the generated url, I get and 404 Not Found. As soon as the token has another value (exchange last letter from token with any other letter, so it gets invalid) it says 401 again.

Maybe this helps?

It seems that the token gets recognized if provided.

Example url:

http://myplex:32400/photo/:/transcode?width=150&height=250&url=http%3A%2F%2Fs2.kluthr.de%3A32400%2Flibrary%2Fmetadata%2F996%2Fthumb%2F1418395105&X-Plex-Token=mytoken

**Comment by bonyboy** [comment]
I'm having the same issue. 
* Running cli.php over LAN with LAN IP and PMS on another machine doesn't give me the error. 
* Changing the IP of the PMS in cli.php to a WAN address on the local machine running Plex-Export still lets me run cli.php without getting the errors.

**Comment by thenet** [comment]
Replace Line 582 with 
`$source_url = "http://127.0.0.1:32400/".substr($thumb_url,1); # e.g. http://local:32400/library/metadata/123/thumb?=date`

The Source URL in the parameter somehow always has to be on localhost, as it is processed on the local server. Works fine for me with non-localhost server.

**Comment by smccloud** [comment]
Any idea how to handle scanning a remote host and getting the thumbnails?  I'm running the scan on my webserver but my Plex server lives at home.  The command I run is `php /home/smccloud/public_html/Plex-Export/cli.php -plex-url=http://blah.smccloud.com:32400 -token=Token -sections=Movies`
