### ISSUE TITLE
Music Libraries not exporting

### ISSUE THREAD

**Issue by cmullins83** [Dachande663/Plex-Export#25]
When the export is run (in Windows via command line using XAMPP and also from a LAMP stack) Video libraries show up (e.g. TV Shows, Movies, etc), but audio libraries do not (e.g. Music, Audiobooks, etc).

**Comment by seanvree** [comment]
Yeah, wish there was a way around this.

**Comment by cmullins83** [comment]
I'm actually working on fixing this, I'm almost done.
