### ISSUE TITLE
How do I install simpleXML?

### ISSUE THREAD

**Issue by seanvree** [Dachande663/Plex-Export#26]
Running on Windows10
IIS Webserver
PHP 7.1

```
C:\inetpub\wwwroot\PlexList>php cli.php
14:32:25 Welcome to the Plex Exporter v1
14:32:25 Error: SimpleXML is not enabled
14:32:25 Error: Failed one or more dependancy checks; aborting
```

I have SImplXML enabled on my PHP installation:

Simplexml support	enabled
Revision	$Id: 7e5516dcdf2fe6ded7970eaeb6abd8d07df39a2a $
Schema support	enabled

**Comment by cmullins83** [comment]
This seems more of an issue with IIS. Have you tried restarting after enabling the module?
I have had success with XAMPP if you can't get IIS working.
