### ISSUE TITLE
Error: Plex library could not be found

### ISSUE THREAD

**Issue by si-hb** [Dachande663/Plex-Export#27]
I have Plex running on the local machine (http://localhost:32400). Here is my output:

```
howard@Plex:~/Downloads/Plex-Export-master$ php cli.php
12:35:24 Welcome to the Plex Exporter v1
12:35:24 Searching for sections in the Plex library at http://localhost:32400/
12:35:24 Error: The Plex library could not be found at http://localhost:32400/
12:35:24 Error: Could not load section data, aborting
howard@Plex:~/Downloads/Plex-Export-master$ 
```

**Comment by cmullins83** [comment]
You need to pass your token. From the documentation:
Notes2:
	* If your Plex Server is running in Home mode, we need to authenticate via a token
	* To get a valid token for your system, look here: https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token
	* Then when running cli.php, add a parameter like: -token=<Your Token>

**Comment by si-hb** [comment]
Thank you for the help, I found the token and the php file ran fine this time. I did try this originally, but missed the part that said "View the XML file..." to see the token value.

Perhaps the error message could alert the user that a missing token was the cause?

**Comment by cmullins83** [comment]
No problem, I missed this a few times myself. I also noticed it will do it if you forget the protocol (http:// or https://) I'm working on a fork to get music working, I'll include your suggestion. Thanks!

**Comment by si-hb** [comment]
One more issue, after generating the .js file and the thumbnails, my browser never loads. Tried Chrome and Firefox. This is all I see:

![image](https://user-images.githubusercontent.com/1800110/30326639-2bd8511a-9797-11e7-9a24-bd6f8bd16f54.png)

**Comment by cmullins83** [comment]
Hi si-hb, you are opening it with the file protocol, this needs to be hosted on something that can handle hosting such as nginx or Apache. If you are Windows or Mac , I'd suggest xampp (https://www.apachefriends.org/index.html), if you are on Linux, I'd just suggest installing Apache2.
Once you have installed XAMPP, browse to the folder you installed it in, and copy the output into the htdocs folder. Then start the xampp control panel, click start on apache, and browse to http://localhost/<WhateverFolderYouPutInHtdocs>.
![capture](https://user-images.githubusercontent.com/12902393/30329203-4203fae8-9797-11e7-8c25-bd5ed49dd169.JPG)

**Comment by Dachande663** [comment]
As @cmullins83 said, browsers do not allow Plex to load the data using file:// protocol. Closing issue.
