### ISSUE TITLE
Download files from PlexExport web

### ISSUE THREAD

**Issue by zaikar** [Dachande663/Plex-Export#28]
Hi,
I think it would be ideal to add the capability to download the files directly from the PlexExport generated page.
I mean like being able to add the path or some handy procedure.

Many thanks

**Comment by ukdtom** [comment]
Since the last change to the source-code was 3 years ago, I doubt any changes to it will happen

**Comment by nwithan8** [comment]
@zaikar try forking it. Looks like if you could add the file URL to the variables, then integrate that into the finally generated HTML file.

**Comment by zaikar** [comment]
I wish I have the knowledge to do that :)

**Comment by Dachande663** [comment]
Plex Export is no longer under active development. For sharing files, I would recommend using the share library functionality built into Plex itself now.
