### ISSUE TITLE
It doesn´t load anything

### ISSUE THREAD

**Issue by flunurtumo** [Dachande663/Plex-Export#29]
After executing the php cli.php -token=mytoken it scans the full database and creates the data.js and the thumbnails in the plex-data folder, but when I open index.html into Firefox or Chrome it loads without any content... what I am missing?

**Comment by ukdtom** [comment]
A webserver?

I'll not work directly from the filesystem

**Comment by flunurtumo** [comment]
You´re right ukdtom, in a webserver it works like a charm! 
Sorry for that! (completely noob)
