### ISSUE TITLE
index.html has dangerous URL redirection on links at bottom of page

### ISSUE THREAD

**Issue by harisimae** [Dachande663/Plex-Export#30]
Just a warning to those that are using this code to update the lines located near the bottom of the index.html. This issue is found in the master. I'm not sure when these got added but they have nothing to do with Plex and redirect links to potentially dangerous pop ups. 

> <div id="footer">
		<p><a href="http://l0ke.com/bl">Plex</a> + <a href="http://l0ke.com/bb">Plex Export </a><span id="last_updated"></span></p>
	</div>

Either remove the links or change them e.g

> <div id="footer">
		<p><a href="https://www.plex.tv">Plex</a> + <a href="http://www.reddit.com/r/PleX/">Plex on Reddit </a><span id="last_updated"></span></p>
	</div>

Here I have the 'Plex' link redirecting to the Plex website and have changed the 'Plex Export' link to Plex on Reddit as I can't recommend this release until it is fixed.

**Comment by OmgImAlexis** [comment]
I've reported this to Github.

**Comment by Dachande663** [comment]
These are legacy links to a redirect domain I used to use. I’ll update to point to the original domains.

**Comment by OmgImAlexis** [comment]
@Dachande663 only reported it as wasn't sure if you would see the notification.

**Comment by Dachande663** [comment]
No worries. Thank you for the heads up. Links replaced.
