### ISSUE TITLE
Save list to txt file

### ISSUE THREAD

**Issue by cameter** [Dachande663/Plex-Export#33]
Is it possible to be able to set this up so that it can be run and once run it ill save the missing episode list into a TXT file.

**Comment by ukdtom** [comment]
Huh....

Plex-Export has nothing at all to do with missing episodes!

It "simply" dumps your libraries into a read-only website

**Comment by cameter** [comment]
apologies. I as working on various things at once and accidentally put this onto plex-export rather that the series scan GitHub.
