### ISSUE TITLE
Doesn't seem to load the data locally

### ISSUE THREAD

**Issue by shaftzy** [Dachande663/Plex-Export#38]
Export went fine, my plex-data folder is full of thumbnails and the plex-data/data.js file contains all of my movies/tv shows etc.

However the index.html page doesnt load the data itself. Just shows a "Loading data from PLEX..." on the page along with html elements. The path's all look correct to me, so I'm not sure what the issue is.

Any ideas?

Windows 10 Home
PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )

**Comment by ukdtom** [comment]
You need to host in on a webserver with PHP support

**Comment by shaftzy** [comment]
Oh right.

For anyone else, here's how to get it working on Win 10 Home, I made a guide here:

https://github.com/Dachande663/Plex-Export/wiki/Windows-10-guide
