### ISSUE TITLE
Slow with lots of movies

### ISSUE THREAD

**Issue by jandersonthegreat** [Dachande663/Plex-Export#44]
So I set up plex export as a remote web page, and in trying to load it, it loads relatively wee, but upon loading all the entries, it immediately brings chrome and the whole pc it's on (which has 32gb of ram) to a crawl.
For reference, my total library items equal 141,919, so I have a pretty big library.  I'm assuming it's because it loads everything at once.  Can it be made to not do this so the page is actually usable for large libraries?

**Comment by Dachande663** [comment]
That is... quite a lot more content than anyone else I've seen. There is a new rework coming that includes more lazy load handling, it could help but fundamentally that's a lot of data to pass.
